"""Export a fixture database into bulk-loadable artifacts.

    python -m seeds.export --db var/test.db --out var/out --format csv,jsonl

CSV uses Postgres' `\copy` conventions (comma, quote-double, header row, `\\N` for
NULL, hex `\\x..` blobs) so loading a 30k-account fixture into staging is one
script rather than a translation layer. JSONL is for test harnesses: one object
per line, `json.loads` and hand it to your ORM/factory.

Plaintext passwords are never part of this: `credentials` exports
algo/salt/iterations/hash exactly as stored, which is what a target app needs in
order to verify the fixture password.
"""

from __future__ import annotations

import argparse
import csv
import json
import sqlite3
import time
from datetime import UTC, datetime
from pathlib import Path

from .db import connect, get_meta

TABLES: dict[str, dict[str, object]] = {
    # table -> {columns, hex_columns}
    "users": {"columns": [
        "id", "username", "email", "email_domain", "display_name", "dob", "country", "region",
        "timezone", "locale", "signup_ts", "signup_ip", "signup_ua", "device_class", "source",
        "invited_by", "status", "verified_ts", "has_phone", "newsletter", "bio", "avatar_seed",
        "is_synthetic_abuse"], "hex": []},
    "credentials": {"columns": ["user_id", "algo", "salt", "iterations", "hash"], "hex": ["salt", "hash"]},
    "sessions": {"columns": [
        "id", "user_id", "token", "ip", "ua", "device_class", "created_ts", "last_seen_ts", "revoked"],
        "hex": []},
    "events": {"columns": ["id", "user_id", "ts", "kind", "weight", "ip", "meta"], "hex": []},
    "invite_edges": {"columns": ["inviter", "invitee", "ts"], "hex": []},
    "flags": {"columns": ["user_id", "rule", "score", "detail", "run_ts"], "hex": []},
}
DEFAULT_TABLES = ("users", "credentials")
POSTGRES_HINTS = """-- Generated by seeds.export. Types assume the Postgres mapping documented in
-- docs/recipes.md; adjust names/types to your schema before running.
--
--   CREATE TABLE users (
--     id bigserial PRIMARY KEY, username citext UNIQUE NOT NULL, email citext UNIQUE NOT NULL,
--     email_domain text, display_name text, dob date, country char(2), region text, timezone text,
--     locale text, signup_ts timestamptz NOT NULL, signup_ip inet, signup_ua text, device_class text,
--     source text, invited_by bigint REFERENCES users(id), status text NOT NULL,
--     verified_ts timestamptz, has_phone boolean, newsletter boolean, bio text, avatar_seed text,
--     is_synthetic_abuse boolean DEFAULT false
--   );
--   CREATE TABLE credentials (
--     user_id bigint PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
--     algo text NOT NULL, salt bytea NOT NULL, iterations int NOT NULL, hash bytea NOT NULL
--   );
--   -- timestamps arrive as epoch seconds; convert on load:
--   --   to_timestamp("signup_ts") AT TIME ZONE 'UTC'
--   -- bytea arrives as \\x-hex, which COPY accepts natively.
--   -- citext makes the unique constraints case-insensitive, which is what the
--   -- login path relies on (and what the fixture's lower() indexes mirror).
"""


def _cell(value, hexcol: bool, fmt: str) -> object:
    if value is None:
        return "\\N" if fmt == "csv" else None
    if hexcol and isinstance(value, (bytes, bytearray, memoryview)):
        return bytes(value).hex() if fmt == "jsonl" else "\\x" + bytes(value).hex()
    if isinstance(value, (bytes, bytearray)):
        return bytes(value).decode("utf-8", "replace")
    return value


def export_table(conn: sqlite3.Connection, table: str, out_dir: Path, fmts: list[str],
                 limit: int, where: str, args: tuple) -> int:
    spec = TABLES[table]
    cols: list[str] = list(spec["columns"])
    hexcols = set(spec["hex"])
    sql = f"SELECT {', '.join(cols)} FROM {table}"
    if where:
        # Applied verbatim, so it must reference a column that table has: scope
        # with --tables when your predicate is table-specific.
        sql += f" WHERE {where}"
    sql += f" ORDER BY {cols[0]}"
    if limit:
        sql += " LIMIT ?"
        args = (*args, limit)

    writers: dict[str, object] = {}
    handles = []
    paths = []
    for fmt in fmts:
        path = out_dir / f"{table}.{ 'tsv' if fmt == 'tsv' else fmt }"
        fh = path.open("w", newline="" if fmt == "csv" else None)
        handles.append(fh)
        paths.append(path)
        if fmt in ("csv", "tsv"):
            w = csv.writer(fh, delimiter="\t" if fmt == "tsv" else ",", quoting=csv.QUOTE_MINIMAL,
                           lineterminator="\n")
            w.writerow(cols)
            writers[fmt] = w
        else:
            writers[fmt] = fh

    n = 0
    cur = conn.execute(sql, args)
    while True:
        chunk = cur.fetchmany(5000)
        if not chunk:
            break
        for row in chunk:
            vals = tuple(_cell(v, c in hexcols, "csv") for c, v in zip(cols, row, strict=True))
            if "csv" in writers or "tsv" in writers:
                for fmt in ("csv", "tsv"):
                    if fmt in writers:
                        writers[fmt].writerow(vals)  # type: ignore[union-attr]
            if "jsonl" in writers:
                obj = {c: _cell(v, c in hexcols, "jsonl") for c, v in zip(cols, row, strict=True)}
                writers["jsonl"].write(json.dumps(obj, separators=(",", ":"), default=str) + "\n")  # type: ignore[union-attr]
            n += 1
    for fh in handles:
        fh.close()
    return n


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="python -m seeds.export", description=__doc__,
                               formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--db", default="var/test.db")
    p.add_argument("--out", default="var/out")
    p.add_argument("--tables", default=",".join(DEFAULT_TABLES), help=f"any of: {', '.join(TABLES)}")
    p.add_argument("--format", default="csv", help="csv,jsonl or csv,jsonl,tsv")
    p.add_argument("--limit", type=int, default=0, help="cap rows per table (0 = all)")
    p.add_argument("--where", default="", help="SQL predicate applied to every table, e.g. \"status='active'\"")
    p.add_argument("--split", action="store_true", help="also write chunks of 50k rows for parallel \\copy")
    p.add_argument("--quiet", action="store_true")
    a = p.parse_args(argv)

    tables = [t.strip() for t in a.tables.split(",") if t.strip()]
    bad = [t for t in tables if t not in TABLES]
    if bad:
        print(f"unknown table(s): {', '.join(bad)}; known: {', '.join(TABLES)}")
        return 2
    fmts = [f.strip() for f in a.format.split(",") if f.strip()]
    if unknown := [f for f in fmts if f not in ("csv", "jsonl", "tsv")]:
        print(f"unknown format(s): {', '.join(unknown)}")
        return 2
    if not a.where:
        a.where = ""

    out_dir = Path(a.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    conn = connect(a.db)
    # Read metadata while the Row factory is still on, then drop it: tuples are
    # what csv.writer wants and skipping the Row wrapper measurably helps on 1M+ rows.
    seed_hash = get_meta(conn, "fixture_hash")
    seed_params = json.loads(get_meta(conn, "seed_params") or "{}")
    conn.row_factory = None
    t0 = time.perf_counter()

    manifest: dict[str, object] = {
        "source_db": str(a.db),
        "fixture_hash": seed_hash,
        "seed_params": seed_params,
        "generated": datetime.now(UTC).isoformat(timespec="seconds"),
        "format": fmts,
        "tables": {},
        "notes": "NULL is \\N; bytea is \\x-hex; timestamps are epoch seconds UTC; no plaintext credentials",
    }
    total_rows = 0
    for table in tables:
        try:
            count = export_table(conn, table, out_dir, fmts, a.limit, a.where, ())
        except sqlite3.OperationalError as exc:
            print(f"  {table:<14} skipped ({exc}) -- --where must use that table's columns")
            manifest["tables"][table] = {"rows": 0, "error": str(exc)}
            continue
        available = conn.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
        manifest["tables"][table] = {"rows": count, "columns": TABLES[table]["columns"],
                                     "available_rows": available}
        total_rows += count
        if not a.quiet:
            print(f"  {table:<14}{count:>9,} rows -> {', '.join(sorted(fmts))}"
                  + (f" (of {available:,})" if a.limit else ""))

    (out_dir / "export.json").write_text(json.dumps(manifest, indent=2, sort_keys=True))
    copy_stmts = [
        f"\copy {tbl} ({', '.join(TABLES[tbl]['columns'])}) FROM '{out_dir / (tbl + '.csv')}' WITH "
        f"(FORMAT csv, HEADER true, NULL '\\N');"
        for tbl in tables
    ]
    # The CSV carries explicit ids, so the sequences are behind every loaded row;
    # without this bump the app's next INSERT collides with fixture id 1..N.
    bump = [
        f"SELECT setval(pg_get_serial_sequence('{tbl}', 'id'), "
        f"(SELECT COALESCE(MAX(id), 1) FROM {tbl}));"
        for tbl in tables if "id" in TABLES[tbl]["columns"]
    ]
    (out_dir / "import.postgres.sql").write_text(
        POSTGRES_HINTS + "\n".join(copy_stmts + bump) + "\n"
    )
    if a.split:
        # `\copy` is single-threaded per table; chunked files let you load in
        # parallel (and retry one piece instead of a whole table).
        for table in tables:
            src = out_dir / f"{table}.csv"
            if not src.exists():
                continue
            lines = src.read_text().splitlines(keepends=True)
            header, body = lines[:1], lines[1:]
            for i in range(0, len(body), 50_000):
                (out_dir / f"{table}.{i // 50_000:03d}.csv").write_text("".join(header + body[i: i + 50_000]))
    conn.close()

    if not a.quiet:
        print(f"exported {total_rows:,} rows to {out_dir} in {time.perf_counter() - t0:.1f}s "
              f"(manifest: export.json, loader: import.postgres.sql)")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
